# -*- coding: utf-8 -*-
"""miniproject_machine_learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mTNbh8qaup5tee6UEx69BUC5MILpzBqr
"""

from google.colab import files

files.upload()

!mkdir -p ~/.kaggle
!mv kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

# Install Kaggle API
!pip install kaggle

# Import and authenticate
from kaggle.api.kaggle_api_extended import KaggleApi
api = KaggleApi()
api.authenticate()

!kaggle datasets download -d osmi/mental-health-in-tech-survey
!unzip mental-health-in-tech-survey.zip # Unzip the downloaded file

import pandas as pd

df = pd.read_csv('survey.csv')
print(df.head().to_markdown(index=False, numalign="left", stralign="left"))  # Display the first few rows
print(df.info())  # Get information about columns, data types, and missing values
print(df.describe().to_markdown(numalign="left", stralign="left"))  # Summary statistics for numerical columns

unique_genders = df['Gender'].unique()
gender_table = pd.DataFrame(unique_genders, columns=['Unique Genders'])
gender_table.to_csv('/content/unique_genders.csv', index=False)

from google.colab import drive
drive.mount('/content/drive')

import shutil
shutil.copy('survey_cleaned.csv', '/content/drive/MyDrive/survey_cleaned.csv')  # Change path if needed

import pandas as pd

# Load the datasets
survey_df = pd.read_csv('survey.csv')
mapping_df = pd.read_csv('/content/Unique Genders - Sheet1.csv')

# Create a dictionary for mapping
gender_mapping = dict(zip(mapping_df['Unique Genders'], mapping_df['define']))

# Replace values in the survey DF and mark for deletion
survey_df['Gender'] = survey_df['Gender'].map(gender_mapping).fillna('delete')

# Remove rows marked for deletion
survey_df = survey_df[survey_df['Gender'] != 'delete']

# Filter by age
survey_df = survey_df[(survey_df['Age'] >= 18) & (survey_df['Age'] <= 72)]

# Drop columns
survey_df = survey_df.drop(columns=['Timestamp', 'state', 'comments'])

# Save the cleaned DataFrame
survey_df.to_csv('survey_cleaned.csv', index=False)


# Copy the cleaned file to Drive
import shutil
shutil.copy('survey_cleaned.csv', '/content/drive/MyDrive/survey_cleaned.csv')  # Adjust path if needed

df = pd.read_csv('survey_cleaned.csv')
print(df.head().to_markdown(index=False, numalign="left", stralign="left"))  # Display the first few rows
print(df.info())  # Get information about columns, data types, and missing values
print(df.describe().to_markdown(numalign="left", stralign="left"))  # Summary statistics for numerical columns