# -*- coding: utf-8 -*-
"""week3/project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ajsv0CSZ8DLlbtT0s9eP1wZFg3-NIns6
"""

import random

class Game:
    def get_user_item(self):
        item = input("Select (r)ock, (p)aper, or (s)cissors: ").lower()
        while item not in ['r', 'p', 's']:
            item = input("Invalid choice. Choose again: (r)ock, (p)aper, or (s)cissors: ").lower()
        item_full = {'r': 'rock', 'p': 'paper', 's': 'scissors'}
        return item_full[item]

    def get_computer_item(self):
        return random.choice(['rock', 'paper', 'scissors'])

    def get_game_result(self, user_item, computer_item):
        if user_item == computer_item:
            return 'draw'
        elif (user_item == 'rock' and computer_item == 'scissors') or \
             (user_item == 'scissors' and computer_item == 'paper') or \
             (user_item == 'paper' and computer_item == 'rock'):
            return 'win'
        else:
            return 'loss'

    def play(self):
        user_item = self.get_user_item()
        computer_item = self.get_computer_item()
        result = self.get_game_result(user_item, computer_item)
        message = f"You chose: {user_item[0]}. The computer chose: {computer_item[0]}. Result: "
        if result == 'win':
            message += "win"
        elif result == 'draw':
            message += "draw"
        else:
            message += "loss"
        print(message)
        return result

def get_user_menu_choice():
    print("Menu:")
    print("(g) Play a new game")
    print("(x) Show scores and exit")
    choice = input(": ")
    while choice not in ['g', 'x']:
        choice = input("Invalid input. Please choose (g) or (x): ")
    return choice

def print_results(results):
    print("Game Results:")
    print(f"You won {results.get('win', 0)} times")
    print(f"You lost {results.get('loss', 0)} times")
    print(f"You drew {results.get('draw', 0)} times")
    print("Thank you for playing!")

def main():
    results = {'win': 0, 'loss': 0, 'draw': 0}
    while True:
        choice = get_user_menu_choice()
        if choice == 'x':
            print_results(results)
            break
        elif choice == 'g':
            game = Game()
            result = game.play()
            results[result] += 1

main()