# -*- coding: utf-8 -*-
"""week1-day4-xp-all.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/alexanderluzhkov/ad1462ed24463e6bb7180cc2add0172f/week1-day4-xp-all.ipynb
"""

my_list=list(range(1,21))
for index, value in enumerate(my_list):
  if index % 2 == 0:
    print (value)

my_fav_numbers = {1,2,3}
my_fav_numbers.add(6)
my_fav_numbers.add(7)
my_fav_numbers.remove(7)
friend_fav_numbers = {7,6,8}
our_fav_numbers = my_fav_numbers.union(friend_fav_numbers)
print(our_fav_numbers)

basket = ["Banana", "Apples", "Oranges", "Blueberries"]
basket.remove('Banana')
basket.insert(0,'Apples')
basket.append('Kiwi')
counter=0
for frut in basket:
  if frut == 'Apples':
    counter+=1
print(counter)
basket.clear()

print(basket)

lst = []
for num in range(1,9):
  val = 1 + num*0.5
  lst.append(val)
print(lst)

my_name = 'Alexander'
while True:
  name = input('what is your name?')
  if name == my_name:
    break
print('wow! Like mine')

lst_of_fruts = input('Type your favorite fruts. Pls, separate the fruits with a single space').split()
print(lst_of_fruts)
frut = input('Type a name of any fruts')
if frut in lst_of_fruts:
  print('You chose one of your favorite fruits! Enjoy!')
else:
  print('You chose a new fruit. I hope you enjoy')

lst_of_ages = input('write your ages, pls. separate your ages with a single space').split()
print(lst_of_ages)
cost_of_tikets = 0
price_to_3 = 0
price_3_to_12 = 10
price_up_to_12 = 15
for age in lst_of_ages:
  if int(age) < 3:
    cost_of_tikets += price_to_3
  elif 3<= int(age) <=12:
    cost_of_tikets += price_3_to_12
  else:
    cost_of_tikets += price_up_to_12
print(cost_of_tikets)

lst_of_names = ['Mike', 'Bill', 'Bob']
names_to_remove = []
for name in lst_of_names:
  age = input(f'{name}, pls, type your age  ')
  if 16 < int(age) < 21:
     names_to_remove.append(name)
for name in names_to_remove:
  lst_of_names.remove(name)
print(lst_of_names)

toppings = []
counter=0
while True:
  topping = input('What pizza topping do you want?  When finish chousing tape /quit/ ')
  if topping == 'quit':
    break
  print(f'You have chousen {topping}')
  toppings.append(topping)
  counter+=1
total_price = 10+2.5*counter
print(f'''Your mouthwatering pizza will be perfectly backed with a folowing array of toppings: {toppings}
      the Total price: {total_price}''')

sandwich_orders = ["Tuna sandwich", "Pastrami sandwich", "Avocado sandwich", "Pastrami sandwich", "Egg sandwich", "Chicken sandwich", "Pastrami sandwich"]
while "Pastrami sandwich" in sandwich_orders:
  sandwich_orders.remove("Pastrami sandwich")
#print(sandwich_orders)
finished_sandwiches = []
for sandwich in list(sandwich_orders):
  sandwich_orders.remove(sandwich)
  finished_sandwiches.append(sandwich)
  print(f'I made your {sandwich}')