# -*- coding: utf-8 -*-
"""week1/day2/xp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Lojb2-HRsPIk6YNf-JazeIkvKcL2K7ut
"""

print('Hello word \n'*4)

a = 99**3*8
print(a)

computer_brand = 'Dell'
print(f'I have a {computer_brand} computer.')

name = 'Alex'
age = 57
shoe_size = 42
info = f"I'm {name}. My age is {age} and my shoe size is {shoe_size}"
print(info)

a = int(input('Give me a number:'))
b = int(input('Give me another number:'))
if a > b:
  print('Hello Word')
else:
  print('Ups..')

a = int(input('Give me a number:'))
if a%2 ==0:
  print('The number is even')
else:
  print('The number is odd')

my_name = 'Alex'
name = input('Tape your name, pls ')
if my_name == name:
  print('Wow! Like mine')
else:
  print('Ok')

high = int(input('Give me please your high in cm '))
if high > 145:
  print('You are tall enough to ride')
else:
  print('You need to grow some more to ride')