# -*- coding: utf-8 -*-
"""week2/day2/xp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vr1RnjHUi4DdFjZizcpxWkObuJqy5PkH
"""

def calculation(a, b):
    # Your Code
    sum=a+b
    sub=a-b
    return (sum, sub)

res = calculation(40, 10)
print(res)

def display_message():
  print('We are lerning Python')
display_message()

def favorite_book(title):
  print('One of my favorite book is '+ title)
title = 'Alice in Wonderland'
favorite_book(title)

def describe_city(city, country='Israel'):
  print(city+' in the country '+country)


describe_city('Tel Avive')

import random
def compare(num_given):
  num_random = random.randint(1, 100)
  if num_given == num_random:
    print('Congratulation! this is the NUMBER!')
  print('Noops. Your number:', str(num_given), 'the right number:', str(num_random))
compare(6)

def make_shirt(size= 'L',text ='I love Python'):
  print('shirt is '+ size + ' and the text is '+ text)
make_shirt()
make_shirt('L')
make_shirt('M')
make_shirt('XL','WOW')

magician_names = ['Harry Houdini', 'David Blaine', 'Criss Angel']
def show_magicians(magician_names):
  for name in magician_names:
    print(name)

def make_great(magician_names):
  for n in range(len(magician_names)):
    magician_names[n]+=' the Grate'

make_great(magician_names)
show_magicians(magician_names)