# -*- coding: utf-8 -*-
"""Week11/day2/xp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x6-VUo86KjBOkd8e6ml0Xw2diL5ktq24

Exercise 1
"""

import numpy as np

array = np.arange(10)
print(array)

"""Exercise 2"""

import numpy as np

original_list = [3.14, 2.17, 0, 1, 2]

int_array = np.array(original_list, dtype=int)

print(int_array)

"""Exercise 3"""

import numpy as np

array = np.arange(1, 10).reshape(3, 3)
print(array)

"""Exercise 4"""

import numpy as np

array = np.random.rand(4, 5)
print(array)

"""Exercise 5"""

second_row = array[1]

print("\nSecond row:")
print(second_row)

"""Exercise 6"""

import numpy as np

array = np.arange(10)
print("Original array:")
print(array)

# Reverse the array
reversed_array = array[::-1]

# Print the reversed array
print("\nReversed array:")
print(reversed_array)

"""Exercise 7"""

import numpy as np

# Create a 4x4 identity matrix
identity_matrix = np.eye(4, dtype=int)

print(identity_matrix)

"""Exercise 8"""

import numpy as np

array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

array_sum = np.sum(array)

array_average = np.mean(array)

# Print the results
print("Original array:", array)
print("Sum of the array:", array_sum)
print("Average of the array:", array_average)

"""Exercise 9"""

import numpy as np

arr = np.arange(1, 21)

matrix = arr.reshape(4, 5)

# Print the original array and the reshaped matrix
print("Original array:")
print(arr)
print("\nReshaped 4x5 matrix:")
print(matrix)

"""Exercise 10"""

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Extract odd numbers
odd_numbers = arr[arr % 2 != 0]

# Print the original array and the odd numbers
print("Original array:", arr)
print("Odd numbers:", odd_numbers)