# -*- coding: utf-8 -*-
"""Week7/day6/XP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11Ln8TAEFgYZ45E5lhWmViXmJDGiDZDtT
"""

# Exercise 1
from google.colab import files

# Upload kaggle.json
files.upload()

# Move it to the correct directory and set permissions
!mkdir -p ~/.kaggle
!mv kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

# Install Kaggle API
!pip install kaggle

from kaggle.api.kaggle_api_extended import KaggleApi

# Authenticate the API
api = KaggleApi()
api.authenticate()

# Define the dataset name and path
dataset = 'titanic'
download_path = '/content/titanic.zip'

# Download the dataset
api.competition_download_file(competition=dataset, file_name='train.csv', path=download_path)
api.competition_download_file(competition=dataset, file_name='test.csv', path=download_path)

# List the contents of the directory to verify download
!ls -lha /content

import pandas as pd

# Define the file path for the CSV file
csv_file_path = '/content/titanic.zip/train.csv'


df = pd.read_csv(csv_file_path)


print("First few rows of the Titanic dataset:")
print(df.head())

# Exercise 2

!wget -O /content/iris.csv https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data


import pandas as pd

# Define column names
column_names = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']

# Load the CSV file into a DataFrame
df = pd.read_csv('/content/iris.csv', header=None, names=column_names)

# Step 3: Display the first five rows of the dataset
print("First five rows of the Iris dataset:")
print(df.head())

# Exercise 3
import requests
import pandas as pd


url = 'https://jsonplaceholder.typicode.com/posts'
response = requests.get(url)

if response.status_code == 200:
    print("Successfully fetched the JSON data.")
else:
    print(f"Failed to fetch data. Status code: {response.status_code}")

# Parse the JSON data
json_data = response.json()

# Load the JSON data into a DataFrame
df = pd.json_normalize(json_data)

# Display the first five entries of the data
print("First five entries of the JSON dataset:")
print(df.head())

# Exercise 4
import pandas as pd


!pip install xlrd

# Step 2: Load the Excel file into a DataFrame
file_path = '/content/file_example_XLS_10 (2).xls'
df = pd.read_excel(file_path, engine='xlrd')

# Step 3: Display the first few rows of the dataset
print("First few rows of the Excel dataset:")
print(df.head())

# Exercise 5
excel_file_path = '/content/exported_data.xlsx'

# Export the DataFrame to an Excel file
df.to_excel(excel_file_path, index=False, engine='openpyxl')

print(f"DataFrame has been exported to {excel_file_path}")

json_file_path = '/content/exported_data.json'

# Export the DataFrame to a JSON file
df.to_json(json_file_path, orient='records', lines=True)

print(f"DataFrame has been exported to {json_file_path}")