# -*- coding: utf-8 -*-
"""Week9/day4/xp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XiSak_7wxzxRLp2oZYRQVZYizJJPsDcz
"""

# Exercise 1

import pandas as pd
import numpy as np
from plotnine import ggplot, aes, geom_point, labs, theme_bw

data = pd.DataFrame({
    'x': np.random.rand(20),
    'y': np.random.rand(20)
})

plot = (
    ggplot(data, aes(x='x', y='y')) +
    geom_point() +
    labs(title='Basic Scatter Plot', x='X-Value', y='Y-Value') +
    theme_bw()
)

# Display the plot
print(plot)

# Exercise 2

import pandas as pd
import numpy as np
from plotnine import ggplot, aes, geom_bar, labs

np.random.seed(0)  # For reproducibility
categories = np.random.choice(['A', 'B', 'C'], size=30)
df = pd.DataFrame({'category': categories})

# Creating the bar plot using Plotnine
bar_plot = (
    ggplot(df, aes(x='category')) +
    geom_bar() +
    labs(
        title='Category Frequency',
        x='Category',
        y='Count'
    )
)

bar_plot

# Exercise 3

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


x = np.linspace(0, 10, 100)
y1 = np.sin(x)
y2 = np.cos(x)
df = pd.DataFrame({'x': x, 'y1': y1, 'y2': y2})

# Plotting y1 and y2 against x in the same plot
plt.figure(figsize=(10, 6))
plt.plot(df['x'], df['y1'], label='sin(x)', color='blue')
plt.plot(df['x'], df['y2'], label='cos(x)', color='red')
plt.xlabel('X-Value')
plt.ylabel('Y-Value')
plt.title('Comparison of Two Functions')
plt.legend()
plt.show()

# Exercise 4

import plotly.graph_objects as go

months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
sales = [200, 210, 250, 300, 320, 340, 360, 380, 390, 400, 420, 440]

# Creating the line chart
fig = go.Figure(data=go.Scatter(x=months, y=sales, mode='lines+markers'))

# Adding title and labels
fig.update_layout(
    title='Monthly Sales Data',
    xaxis_title='Month',
    yaxis_title='Sales'
)

fig.show()

# Exercise 5

import plotly.graph_objects as go

genres = ['Fiction', 'Non-Fiction', 'Sci-Fi', 'Mystery', 'Biography']
books_sold = [120, 150, 90, 80, 130]

# Creating the bar chart
fig = go.Figure(data=[go.Bar(x=genres, y=books_sold, marker_color=['blue', 'green', 'orange', 'red', 'purple'])])

# Adding title and labels
fig.update_layout(
    title='Books Sold by Genre',
    xaxis_title='Genre',
    yaxis_title='Books Sold'
)

fig.show()

# Exercise 6

import plotly.express as px
import pandas as pd

data = pd.DataFrame({
    'Age': [25, 30, 35, 40, 45],
    'Salary': [50000, 60000, 70000, 80000, 90000],
    'Years of Experience': [2, 5, 7, 10, 12]
})

# Creating the scatter plot
fig = px.scatter(data, x='Age', y='Salary', size='Years of Experience',
                 title='Relationship between Age, Salary, and Experience')

fig.show()