# -*- coding: utf-8 -*-
"""week4/miniproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Kgxfq_iNyDic3k4C6ibXMRfjVkBWXF6
"""

from google.colab import files
uploaded = files.upload()

class AnagramChecker:
    def __init__(self, filepath):

        with open(filepath, 'r', encoding='utf-8') as file:
            self.words = set(word.strip().upper() for word in file.readlines())

    def is_valid_word(self, word):

        return word.upper() in self.words

    def is_anagram(self, word1, word2):

        return sorted(word1.upper()) == sorted(word2.upper()) and word1.upper() != word2.upper()

    def get_anagrams(self, word):

        return [w for w in self.words if self.is_anagram(word, w)]

def main():
    checker = AnagramChecker('sowpods.txt')
    while True:
        print("\nMenu:")
        print("1. Check a word")
        print("2. Exit")
        choice = input("Choose an option: ")

        if choice == '2':
            print("Goodbye!")
            break
        elif choice == '1':
            user_word = input("Enter a single word: ").strip()
            if ' ' in user_word or not user_word.isalpha():
                print("Error: Please enter only a single, alphabetic word.")
                continue

            if checker.is_valid_word(user_word):
                anagrams = checker.get_anagrams(user_word)
                if anagrams:
                    anagrams_str = ', '.join(anagrams)
                    print(f"YOUR WORD: '{user_word.upper()}'\nThis is a valid English word.\nAnagrams for your word: {anagrams_str}.")
                else:
                    print(f"YOUR WORD: '{user_word.upper()}'\nThis is a valid English word.\nNo anagrams found.")
            else:
                print(f"YOUR WORD: '{user_word.upper()}'\nThis is not a valid English word.")
        else:
            print("Invalid option, please choose again.")

main()