# -*- coding: utf-8 -*-
"""week1/day4/challenge&class.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TTN9MXXpbgH3AIWQMrZSGb6VpRSNX5X6
"""

list1 = [5, 10, 15, 20, 25, 50, 20]
print(list1.index(20))
list1[3]=200
print(list1)

list1 = [-5, 10, 15, 20, 25, 50, 20]
max_num = list1[0]
for num in list1:
  if num > max_num:
    max_num = num
print(max_num)

num = int(input('give a number:'))
for x in range(1,11):
  print(f" {num} * {x} = {num*x}")

num = int(input('give a number:'))
counter = 0
while counter <= num-1:
  counter +=1
  if counter%2 ==0:
    continue
  else:
    print(counter)

my_list =  ["level", "world", "madam", "python", "racecar", "hello", "civic"]
polydroms = []
for sub_list in my_list:
  new_sub_list = sub_list[::-1]
  if sub_list == new_sub_list:
    polydroms.append(sub_list)
print(polydroms)

num = int(input('Give me a number: '))
length = int(input('Give me a length: '))
lst_result = []
char = num
while len(lst_result) < length:
    lst_result.append(char)
    char +=num
print(lst_result)

string = input('Give me a string: ')
new_string = string[0]
for char in string:
  if char not in new_string:
    new_string +=char

print(new_string)