# -*- coding: utf-8 -*-
"""week1/day6/challenge.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1whsoe7NfQgF0XO3Ij1NLIynPYS09ndcl
"""

given_word = input('Give me a word: ')
enumerated_letters = list(enumerate(list(given_word)))
lst = [(b,a) for a,b in enumerated_letters]
dict_result = {}
for item in lst:
    key, value = item
    if key in dict_result:
        dict_result[key].append(value)
    else:
        dict_result[key] = [value]
print(dict_result)

items_purchase = items_purchase = {
  "Apple": "$4",
  "Honey": "$3",
  "Fan": "$14",
  "Bananas": "$4",
  "Pan": "$100",
  "Spoon": "$2"}
wallet = "$100"
number_wallet = wallet.replace("$", "")
number_wallet = int(number_wallet)
for key, value in items_purchase.items():
    number_string = value.replace("$", "")
    number = int(number_string)
    items_purchase[key] = number
sorted_items_purchase = sorted(items_purchase.items(), key=lambda x: x[1])
result = []
total = 0
for item, number in sorted_items_purchase:
    total += number
    if total < number_wallet:
        result.append(item)
    else:
        break
if result ==[]:
  print ("Nothing")

print(result)