# -*- coding: utf-8 -*-
"""Week4/day2/challenge.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cYEkOy69_Gmwd10ZlW-3koLinyyuedss
"""

import math

class Circle:
    def __init__(self, radius=None, diameter=None):
        if radius is not None:
            self.radius = radius
        elif diameter is not None:
            self.radius = diameter / 2
        else:
            raise ValueError("Please specify either radius or diameter")


    @property
    def area(self):
        return math.pi * (self.radius ** 2)

    def __str__(self):
        return f"Circle with radius: {self.radius}"

    def __repr__(self):
        return f"Circle(radius={self.radius})"

    def __add__(self, other):
        return Circle(radius=self.radius + other.radius)

    def __lt__(self, other):
        return self.radius < other.radius

    def __eq__(self, other):
        return self.radius == other.radius

    def __gt__(self, other):
        return self.radius > other.radius

# Testing
c1 = Circle(radius=3)
c2 = Circle(diameter=4)

print(c1)
print(c2)

print("Area of c1:", c1.area)
print("Area of c2:", c2.area)

c3 = c1 + c2
print("c3:", c3)

print("Is c1 bigger than c2?", c1 > c2)
print("Are c1 and c2 equal?", c1 == c2)

circle_list = [c1, c2, c3]
circle_list.sort()
print("Sorted circles:", circle_list)