# -*- coding: utf-8 -*-
"""week4/day4/challenge.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fxAQ1oZCi__3JdP4KgA5toPyE34LIVWH
"""

from google.colab import files
uploaded = files.upload()

class Text:
    def __init__(self, text):
        self.text = text.lower()
    def word_frequency(self, word):
        words = self.text.split()
        frequency = words.count(word.lower())
        if frequency == 0:
            return "The word does not exist in the text."
        else:
            return frequency

    def most_common_words(self):
        words = self.text.split()
        if not words:
            return None
        word_counts = {}
        for word in words:
            if word in word_counts:
                word_counts[word] += 1
            else:
                word_counts[word] = 1

        max_frequency = max(word_counts.values())
        most_common = [word for word, count in word_counts.items() if count == max_frequency]
        return most_common

    def unique_words(self):
        words = set(self.text.split())
        return list(words)

    @classmethod
    def from_file(cls, filename):

        with open(filename, 'r', encoding='utf-8') as file:
            text = file.read()
        return cls(text)


text_instance = Text.from_file('the_stranger.txt')

print("Most common words:", text_instance.most_common_words())
print("Unique words:", text_instance.unique_words())
print ("Frequency of 'why':", text_instance.word_frequency("why"))