# -*- coding: utf-8 -*-
"""Week8/day2/challenge.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o2UL-1q3gMk39TjiXzzGE0DhuIkN48i9
"""

!pip install kaggle pandas numpy scikit-learn

import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
import zipfile
import os

# Create a folder to store the dataset
#!mkdir -p datasets

# Download and unzip the dataset
#!kaggle datasets download -d ruchi798/data-science-job-salaries -p datasets
#with zipfile.ZipFile('datasets/data-science-job-salaries.zip', 'r') as zip_ref:
    #zip_ref.extractall('datasets')

# Load the dataset into a pandas DataFrame
df = pd.read_csv('/content/datasets/ds_salaries.csv')

# Normalize the 'salary' column using Min-Max normalization
scaler = MinMaxScaler()
df['salary_normalized'] = scaler.fit_transform(df[['salary_in_usd']])

# Drop the 'salary' and 'salary_currency' columns
df_reduced = df.drop(columns=['salary', 'salary_currency'])


# Group by 'experience_level' and calculate average and median salaries
grouped_data = df_reduced.groupby('experience_level').agg(
    average_salary=pd.NamedAgg(column='salary_normalized', aggfunc='mean'),
    median_salary=pd.NamedAgg(column='salary_normalized', aggfunc='median')
).reset_index()

# Define the order for experience levels
ordered_experience_levels = ['EN', 'MI', 'SE', 'EX']
grouped_data['experience_level'] = pd.Categorical(grouped_data['experience_level'],
                                                  categories=ordered_experience_levels,
                                                  ordered=True)

# Sort the results by the defined order
grouped_data = grouped_data.sort_values('experience_level')

# Display the results
grouped_data

