# -*- coding: utf-8 -*-
"""Week8/day6/daychallenge.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tUe_jYDGvGyvunpaPPdmfam6XFsaEJUn
"""

!pip install -q kaggle

from google.colab import files
files.upload()

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

# Download the dataset from Kaggle
!kaggle datasets download -d unsdsn/world-happiness

# Unzip the dataset
!unzip world-happiness.zip -d world_happiness

# Import necessary libraries
import pandas as pd
import matplotlib.pyplot as plt

# Load the 2019 data
data_2019 = pd.read_csv('world_happiness/2019.csv')

# Display the first few rows to understand the structure
print(data_2019.head())

# Display summary information about the data
print(data_2019.info())

# Check for missing values
print(data_2019.isnull().sum())

# Relationship between Social Support and Happiness Score

plt.figure(figsize=(10, 6))
plt.scatter(data_2019['Social support'], data_2019['Score'], c='blue', alpha=0.5)
plt.title('Relationship between Social Support and Happiness Score')
plt.xlabel('Social Support')
plt.ylabel('Happiness Score')
plt.grid(True)
plt.show()

# GDP per Capita and Healthy Life Expectancy for different countries

# Select first five and last five countries
first_five = data_2019.head(5)
last_five = data_2019.tail(5)

# Prepare the figure
fig, axs = plt.subplots(2, 1, figsize=(14, 10))

# Plot for first five countries
axs[0].bar(first_five['Country or region'], first_five['GDP per capita'], color='blue', alpha=0.6, label='GDP per Capita')
axs[0].plot(first_five['Country or region'], first_five['Healthy life expectancy'], color='red', marker='o', label='Healthy Life Expectancy')
axs[0].set_title('GDP per Capita and Healthy Life Expectancy for First Five Countries')
axs[0].legend()
axs[0].set_ylabel('Values')
axs[0].set_xticklabels(first_five['Country or region'], rotation=45)

# Plot for last five countries
axs[1].bar(last_five['Country or region'], last_five['GDP per capita'], color='blue', alpha=0.6, label='GDP per Capita')
axs[1].plot(last_five['Country or region'], last_five['Healthy life expectancy'], color='red', marker='o', label='Healthy Life Expectancy')
axs[1].set_title('GDP per Capita and Healthy Life Expectancy for Last Five Countries')
axs[1].legend()
axs[1].set_ylabel('Values')
axs[1].set_xticklabels(last_five['Country or region'], rotation=45)

plt.tight_layout()
plt.show()

#GDP per Capita and Healthy Life Expectancy by Region

# Define region mapping
regions = {
    'Europe': ['Finland', 'Denmark', 'Norway', 'Iceland', 'Netherlands', 'Switzerland', 'Sweden', 'Austria', 'Ireland', 'Germany'],
    'Asia': ['United Arab Emirates', 'Singapore', 'Malaysia', 'Thailand', 'Japan', 'South Korea', 'Hong Kong', 'Taiwan', 'China', 'Vietnam'],
    'Africa': ['Mauritius', 'Libya', 'Nigeria', 'Ghana', 'Senegal', 'Cameroon', 'Ivory Coast', 'Benin', 'Madagascar', 'Chad'],
    'Australia and Oceania': ['Australia', 'New Zealand'],
    'North America': ['Canada', 'United States', 'Mexico'],
    'South America': ['Chile', 'Brazil', 'Argentina', 'Colombia', 'Peru']
}

# Create a new DataFrame for region data
region_data = {'Region': [], 'GDP per capita': [], 'Healthy life expectancy': []}

# Calculate averages for each region
for region, countries in regions.items():
    region_subset = data_2019[data_2019['Country or region'].isin(countries)]
    avg_gdp = region_subset['GDP per capita'].mean()
    avg_life_exp = region_subset['Healthy life expectancy'].mean()
    region_data['Region'].append(region)
    region_data['GDP per capita'].append(avg_gdp)
    region_data['Healthy life expectancy'].append(avg_life_exp)

# Convert to DataFrame
region_df = pd.DataFrame(region_data)

# Display the region averages
print(region_df)

plt.figure(figsize=(14, 8))

# Bar plot for GDP per Capita
plt.bar(region_df['Region'], region_df['GDP per capita'], color='blue', alpha=0.6, label='GDP per Capita')

# Line plot for Healthy Life Expectancy
plt.plot(region_df['Region'], region_df['Healthy life expectancy'], color='red', marker='o', label='Healthy Life Expectancy')

plt.title('GDP per Capita and Healthy Life Expectancy by Region')
plt.xlabel('Region')
plt.ylabel('Values')
plt.xticks(rotation=45)
plt.legend()
plt.grid(True)
plt.show()