# -*- coding: utf-8 -*-
"""week1/day6/exerciseXP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13738ZMe2c8koiEQ-c2YRYwFPHIFKSD2-
"""

keys = ['Ten', 'Twenty', 'Thirty']
values = [10, 20, 30]
my_dict = {k:v for k,v in zip(keys, values)}
print(my_dict)

from __future__ import print_function
family = {"rick": 43, 'beth': 13, 'morty': 5, 'summer': 8}
ages=[]
cost=0
for v in family.values():
  ages.append(v)
for age in ages:
  if int(age)<3:
    cost+=0
  elif 3<=int(age)<=12:
    cost+=10
  else:
    cost+=15
print(f'the family’s total cost for the movies ', cost)

brand={'name': 'Zara',
'creation_date': 1975,
'creator_name': 'Amancio Ortega Gaona',
'type_of_clothes': ['men', 'women', 'children', 'home'],
'international_competitors': ['Gap', 'H&M', 'Benetton'],
'number_stores': 7000,
'major_color': {'France': 'blue',
    'Spain': 'red',
    'US': ['pink', 'green']}}
brand['number_stores']=2
brand['country_creation']= 'Spain'
if 'international_competitors'in brand:
  brand['international_competitors'].append('Desigual')
del brand['creation_date']
print(brand['international_competitors'][-1])
print(f'major_color in US ', brand['major_color']['US'])
print(f'lengh of dict -', len(brand))
print(brand.keys())
more_on_zara={'creation_date': 1975,
'number_stores': 10000}
brand.update(more_on_zara)
print(brand)
print(f'number_stores ',brand['number_stores'])

users = ["Mickey","Minnie","Donald","Ariel","Pluto"]
numbers = list(range(5))
disney_users_A = {k:v for k,v in zip(users, numbers)}
print(disney_users_A)
str_numbers=[str(num) for num in numbers]
disney_users_B={k:v for k,v in zip(numbers, users)}
print(disney_users_B)
sorted_keys=sorted(disney_users_A.keys())
disney_users_C = {k:disney_users_A[k] for k in sorted_keys }
print(disney_users_C)
keys_A=disney_users_A.keys()
i_keys_A=[key for key in keys_A if 'i' in key]
disney_users_I={k:disney_users_A[k] for k in i_keys_A}
print(disney_users_I)
low_keys_A = [name.lower() for name in keys_A]
low_m_p_keys_A=[key for key in low_keys_A if 'm' in key or 'p' in key]
m_p_keys_A = [name.capitalize() for name in low_m_p_keys_A]
disney_users_m_p = {k:disney_users_A[k] for k in m_p_keys_A}
print(disney_users_m_p)