# -*- coding: utf-8 -*-
"""week3/day2/xp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pw6ySgmLREP3Ng4SCwy6jEyaoiofk1rw
"""

class Cat:
    def __init__(self, cat_name, cat_age):
        self.name = cat_name
        self.age = cat_age
ferst_cat = Cat('cat', 5)
second_cat = Cat('citti', 1)
therd_cat = Cat('old cat', 14)

def who_is_oldest_cat(lst_cats):
  oldest_cat = lst_cats[0]
  for cat in lst_cats:
    if cat.age > oldest_cat.age:
      oldest_cat = cat
  return oldest_cat.name
cats=[ferst_cat, second_cat, therd_cat]
oldest_cat = who_is_oldest_cat(cats)
print(oldest_cat)

class Dog:
  def __init__(self,dog_name, dog_hight):
    self.name = dog_name
    self.hight = dog_hight
  def bark(self):
    print(f'{self.name} goes woof')
  def jump(self):
    print(f'{self.name} jumps {2*self.hight} cm high!')
davids_dog = Dog('Rex', 50)
print(f'dogs name {davids_dog.name} dog is {davids_dog.hight} cm high')
davids_dog.bark()
davids_dog.jump()
sarahs_dog = Dog('Teacup', 20)
print(f'dogs name {sarahs_dog.name} dog is {sarahs_dog.hight} cm high')
sarahs_dog.bark()
sarahs_dog.jump()
if davids_dog.hight > sarahs_dog.hight:
  print(f'{davids_dog.name} is higher')
elif davids_dog.hight < sarahs_dog.hight:
  print(f'{sarahs_dog.name} is higher')

class Song:
  def __init__(self, liriks):
    self.liriks = list(liriks)
  def sing_me_a_song(self):
    for liriks in self.liriks:
      print(liriks)
stairway= Song(["There’s a lady who's sure","all that glitters is gold", "and she’s buying a stairway to heaven"])
stairway.sing_me_a_song()

class Zoo:
  def __init__(self,zoo_name):
    self.name = zoo_name
    self.animals = []
  def add_animal(self, new_animal):
    if new_animal not in self.animals:
      self.animals.append(new_animal)
  def get_animals(self):
    print(self.animals)
  def sell_animal(self, animal_sold):
    if animal_sold in self.animals:
      self.animals.remove(animal_sold)
    else:
      print('There is no {animal_sold} in the Zoo')
  def sort_animals(self):
    sorted_animals = {}
    for animal in sorted(self.animals):
      first_letter = animal[0]
      if first_letter not in sorted_animals:
        sorted_animals[first_letter]= [animal]
      else:
         sorted_animals[first_letter].append(animal)
    sorted_animals_num = {num: sorted_animals[group] for num, group in enumerate(sorted_animals, 1)}
    return sorted_animals_num
  def get_groups(self):
    sorted_animals=self.sort_animals()
    for k,v in sorted_animals.items():
      print(k,v)

ramat_gan_safari=Zoo('Ramat gan safari')

ramat_gan_safari.add_animal('Ape')
ramat_gan_safari.add_animal('Baboon')
ramat_gan_safari.add_animal('Bear')
ramat_gan_safari.add_animal('Eal')
ramat_gan_safari.add_animal('Emu')
ramat_gan_safari.add_animal('Cat')
ramat_gan_safari.add_animal('Cougar')
ramat_gan_safari.add_animal('Tiger')
ramat_gan_safari.get_animals()
ramat_gan_safari.sell_animal('Tiger')
ramat_gan_safari.sort_animals()
ramat_gan_safari.get_groups()