# -*- coding: utf-8 -*-
"""week2/day4/xp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xKTqWOAojL2mC3RYsCcd73b42pW3XjRH
"""

import random

def random_integer(season):
  if season == 'winter':
    return random.randint(-10, 16)
  elif season == 'spring':
    return random.randint(5, 25)
  elif season == 'summer':
    return random.randint(20, 40)
  elif season == 'autumn':
    return random.randint(0, 22)

def main(season):
  tem = random_integer(season)
  sentence1 = f'The temperature right now is {tem} degrees Celsius'
  if tem <0:
    sentence2 = 'Brrr, that’s freezing! Wear some extra layers today'
  elif 0 <= tem < 16:
    sentence2 = 'Quite chilly! Don’t forget your coat'
  elif 16 < tem <= 23:
    sentence2 = 'Have a nice day'
  elif 23 < tem <= 32:
    sentence2 = 'It looks like a little bit hot. Be carefull.'
  else:
    sentence2 = "Wery hot today! Don't forget a water"
  return sentence1,  sentence2

input_season = input('Give me a season: ')
print(main(input_season))

data = [
    {
        "question": "What is Baby Yoda's real name?",
        "answer": "Grogu"
    },
    {
        "question": "Where did Obi-Wan take Luke after his birth?",
        "answer": "Tatooine"
    },
    {
        "question": "What year did the first Star Wars movie come out?",
        "answer": "1977"
    },
    {
        "question": "Who built C-3PO?",
        "answer": "Anakin Skywalker"
    },
    {
        "question": "Anakin Skywalker grew up to be who?",
        "answer": "Darth Vader"
    },
    {
        "question": "What species is Chewbacca?",
        "answer": "Wookiee"
    }
]
def my_quiz(lst_of_questions):
  score_right = 0
  score_wrong = 0
  lst_wrong_answers =[]
  for item in lst_of_questions:
    print(item['question'])
    ans_given=input('Your answear is: ')
    if ans_given == item['answer']:
      score_right +=1
    else:
      score_wrong +=1
      lst_wrong_answers.append(ans_given)
  return f'Right answers  {score_right}, wrong answers {score_wrong} list of wrong answers{lst_wrong_answers}'

lst =  [{
        "question": "What is Baby Yoda's real name?",
        "answer": "Grogu"
    }]
print(my_quiz(data))

def get_age(year, month, day):
  current_year = 2024
  current_month = 4
  current_day = 10
  age = int((current_year-year) + (current_month - month)/12 + (current_day-day)/365)
  return age


def can_retire(year,month,day):
  female_ret_age = 62
  male_ret_age = 67
  giv_age = get_age(year, month, day)
  if gender == 'f':
    if giv_age < female_ret_age:
      return 'Keep working'
    else:
      return 'You can be retired'
  elif gender == 'm':
    if giv_age < male_ret_age:
      return 'Keep working'
    else:
      return 'You can be retired'
  else:
    return 'input error'

date_of_birth = input('Give me your date of birth in format yyyy/mm/dd: ')
year, month, day = map(int, date_of_birth.split('/'))
gender = input('Indicate your gender f or m: ')
print(can_retire(year,month,day))

def progression(x):
  lengh = 4
  sum = 0
  list_of_strings = [x * i for i in range(1, lengh + 1)]
  for char in list_of_strings:
    sum = sum + int(char)
  return sum
num = input('type a digit: ')
print(progression(num))