# -*- coding: utf-8 -*-
"""week4/day4/xp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-ptd1PqvhoSb1B_7PvctwpNXL_CmrxYS
"""

import random

def get_words_from_file():

    with open('sowpods.txt', 'r') as file:
            words = file.read().split()
    return words


def get_random_sentence(length, words):
    return ' '.join(random.choices(words, k=length)).lower()

def main():

        length = int(input("How long do you want the sentence to be? (Enter an integer between 2 and 20): "))
        if 2 <= length <= 20:
            words = get_words_from_file()
            if words:
                print("Generating a random sentence...")
                sentence = get_random_sentence(length, words)
                print("Random sentence:", sentence)


if __name__ == "__main__":
    main()

import json

sampleJson = """{
   "company":{
      "employee":{
         "name":"emma",
         "payable":{
            "salary":7000,
            "bonus":800
         }
      }
   }
}"""


data = json.loads(sampleJson)


salary = data["company"]["employee"]["payable"]["salary"]
print("Salary:", salary)


data["company"]["employee"]["birth_date"] = "1991-11-11"


with open('updated_data.json', 'w') as file:
    json.dump(data, file, indent=2)

print("Updated JSON has been saved to 'updated_data.json'.")